# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  start:
    cmds:
      - go run . {{.CLI_ARGS}}
    silent: true

  broadcast:
    cmds:
      - go run . broadcast {{.CLI_ARGS}}
    silent: true
  generate:
    cmds:
      - protoc -I ./proto  --go_out=./proto --go_opt=paths=source_relative --go-grpc_out=./proto --go-grpc_opt=paths=source_relative raft.proto
    silent: true
