# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  start:
    cmds:
      - go run . {{.CLI_ARGS}}
    silent: true

  pb-generate:
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative main.proto
    silent: true
